#! /bin/sh
set -euo pipefail

source ./globals

echo "Agregando dependencias de Linux"
apk add util-linux zip unzip nano flex bison e2fsprogs e2fsprogs-extra

echo "Agregando dependencias para compilar QT6"
apk add qt6-qtbase-dev qt6-qtdeclarative-dev qt6-qtshadertools-dev qt6-qtwayland qt6-qtwayland-dev qt6-qtdeclarative qt6-qtdeclarative-dev cmake ninja build-base \
	qt6-qtquicktimeline-dev qt6-qtquicktimeline

apk add git ninja perl python3 gperf \
    mesa-dev libxkbcommon-dev \
    freetype-dev harfbuzz-dev fontconfig-dev \
    gettext-dev ncurses-dev ncurses-libs \
    mpc1-dev gmp-dev mpfr-dev rsync

apk add linux-headers parted

apk add \
    seatd \
    libseat \
    libseat-dev \
    wayland \
    wayland-dev \
    wayland-protocols \
    wlroots \
    wlroots-dev \
    libinput \
    libinput-dev \
    libdrm-dev \
    xkeyboard-config \
    pixman \
    cage

# Additional dependencies for amd64 architecture
if [ "$SYS_ARCH" == "amd64" ]; then
    apk add --no-cache elfutils-dev zlib-dev \
        libcap-dev openssl-dev gawk diffutils
fi
