#! /bin/sh
set -euo pipefail

WOLFBEAR_APPS_DIR=$( dirname "$(pwd)" )/wolfbear-apps
WOLFBEAR_TOOLS_DIR=$( dirname "$(pwd)" )/wolfbear-tools
QT_DIR=$WOLFBEAR_TOOLS_DIR/dependencies/qt5

echo "Agregando dependencias de Linux"
apk add util-linux zip unzip

echo "Agregando dependencias para compilar QT6"
apk add qt6-qtbase-dev qt6-qtdeclarative-dev qt6-qtshadertools-dev qt6-qtquickcontrols2-dev cmake ninja build-base

apk add git ninja perl python3 gperf \
    mesa-dev libxkbcommon-dev wayland-dev libinput-dev \
    freetype-dev harfbuzz-dev fontconfig-dev
