#! /bin/sh
set -euo pipefail

WOLFBEAR_APPS_DIR=$( dirname "$(pwd)" )/wolfbear-apps
WOLFBEAR_TOOLS_DIR=$( dirname "$(pwd)" )/wolfbear-tools
QT_DIR=$WOLFBEAR_TOOLS_DIR/dependencies/qt5

echo "Agregando dependencias de Linux"
apk add util-linux zip unzip

echo "Agregando dependencias para compilar QT6"
apk add qt6-qtbase-dev qt6-qtdeclarative-dev qt6-qtshadertools-dev cmake ninja build-base

apk add git ninja perl python3 gperf \
    mesa-dev libxkbcommon-dev wayland-dev libinput-dev \
    freetype-dev harfbuzz-dev fontconfig-dev


git clone https://github.com/qt/qtquickcontrols2 -b 6.8.2 $QT_DIR/qtquickcontrols2
cd $QT_DIR/qtquickcontrols2

cmake -B build -S . \
  -DCMAKE_INSTALL_PREFIX=/usr \
  -DCMAKE_PREFIX_PATH=/usr/lib/qt6 \
  -DCMAKE_BUILD_TYPE=Release
  
cmake --build build -j$(nproc)
doas cmake --install build