#!/bin/bash

WOLFBEAR_ALPINE_x86_HOST=192.168.2.2
PATH_TO_WOLFBEAR_OS_TARGET="~/wolfbear-os/target"

echo "Descargando Imagen x86-64"

echo "Eliminando archivos anteriores WolfbearOS_x86-64.img"
rm -f ./target/WolfbearOS_x86-64.img

echo "Descargando nuevos archivos"

mkdir -p ./target
sshpass -p "Naru112" scp ${WOLFBEAR_ALPINE_x86_HOST}:${PATH_TO_WOLFBEAR_OS_TARGET}/generated.img ./target/WolfbearOS_x86-64.img

echo "Descarga Terminada"