#! /bin/sh
set -euo pipefail

source ./globals

cd "$WOLFBEAR_DEN_LAUNCHER_SOURCE_DIR"

BUILD_DIR="$WOLFBEAR_DEN_LAUNCHER_OUTPUT_DIR/build"

rm -rf "$BUILD_DIR"

cmake -S . \
      -B "$BUILD_DIR" \
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_INSTALL_PREFIX=/usr

cmake --build "$BUILD_DIR" -- -j"$(nproc)"

DESTDIR="$WOLFBEAR_DEN_LAUNCHER_OUTPUT_DIR" cmake --install "$BUILD_DIR"