#! /bin/sh
set -euo pipefail

source ./globals

cd "$WOLFBEAR_APPS_OUTPUT_DIR"
mkdir wolfbear-apps

rsync -a --update "$WOLFBEAR_DEN_LAUNCHER_OUTPUT_DIR"/usr/ wolfbear-apps/usr/
rsync -a --update "$WOLFBEAR_PAW_CLI_OUTPUT_DIR"/usr/ wolfbear-apps/usr/

tar -czf wolfbear-apps.tar.gz wolfbear-apps

rm -rf wolfbear-apps
rm -rf "$WOLFBEAR_DEN_LAUNCHER_OUTPUT_DIR"
rm -rf "$WOLFBEAR_PAW_CLI_OUTPUT_DIR"