#! /bin/sh

source ./globals

scp -i ./certs/wolfbear-repo.pem "$COMPILED_LINUX/bzImage" wolfbear@wolfbear.mx:"$WOLFBEAR_REPO_WWW/$WOLFBEAR_VERSION/aarch64/wolfbear-kernel_x86_64"
scp -i ./certs/wolfbear-repo.pem "$COMPILED_LINUX/Image" wolfbear@wolfbear.mx:"$WOLFBEAR_REPO_WWW/$WOLFBEAR_VERSION/aarch64/wolfbear-kernel_aarch64"