#! /bin/sh

source ./globals

cd $ROOT_PATH

scp -i "$WOLFBEAR_REPO_CERT" "$OUTPUT_PATH/apk/apk.zip" wolfbear@wolfbear.mx:"$WOLFBEAR_REPO_WWW/$WOLFBEAR_VERSION/apk"

ssh -i "$WOLFBEAR_REPO_CERT" wolfbear@wolfbear.mx <<ENDSSH
    cd "$WOLFBEAR_REPO_WWW/$WOLFBEAR_VERSION"
    unzip apk.zip
ENDSSH