#! /bin/sh

source ./globals

cd $ROOT_PATH

if [ "$SYS_ARCH" = 'arm64' ]; then
    if [ -f "$BUSYBOX_COMPILED_DIR/busybox.zip" ]; then
        scp -i "$WOLFBEAR_REPO_CERT" "$BUSYBOX_COMPILED_DIR/busybox.zip" wolfbear@wolfbear.mx:"$WOLFBEAR_REPO_WWW/$WOLFBEAR_VERSION/kernel/aarch64/busybox_aarch64.zip"
    fi
fi

if [ "$SYS_ARCH" = 'amd64' ]; then
    if [ -f "$BUSYBOX_COMPILED_DIR/busybox.zip" ]; then
        scp -i "$WOLFBEAR_REPO_CERT" "$BUSYBOX_COMPILED_DIR/busybox.zip" wolfbear@wolfbear.mx:"$WOLFBEAR_REPO_WWW/$WOLFBEAR_VERSION/kernel/x86_64/busybox_x86_64.zip"
    fi
fi