#! /bin/sh
set -euo pipefail

source ./globals

WOLFBEAR_ARCHES="aarch64 x86_64"

WOLFBEAR_PACKAGES="
apk-tools
shadow
util-linux
e2fsprogs
dosfstools
parted
kmod
linux-headers
libc-utils
file
nano
dhcpcd
openresolv
openssh
openssh-server
git
strace
sdl2
sdl2-dev
libdrm
libdrm-dev
mesa-gbm
mesa-dev
mesa-dri-gallium
mesa-egl
libinput
libinput-dev
expat-dev
libffi-dev
libxkbcommon
grub-efi
e2fsprogs-extra
rsync
"

ALPINE_MAIN_REPO="https://dl-cdn.alpinelinux.org/alpine/v3.22/main"
ALPINE_COMMUNITY_REPO="https://dl-cdn.alpinelinux.org/alpine/v3.22/community"

for WOLFBEAR_ARCH in $WOLFBEAR_ARCHES; do
    APK_OUTPUT_SNAPSHOTS="$OUTPUT_PATH/apk/$WOLFBEAR_ARCH"

	echo "Limpiando mirrors anteriores en $APK_OUTPUT_SNAPSHOTS"
	rm -rf "$APK_OUTPUT_SNAPSHOTS"
	mkdir -p "$APK_OUTPUT_SNAPSHOTS"

    echo "Descargando dependencias APK"
	apk fetch \
        --no-cache \
        --cache-dir /dev/null \
        --arch "$WOLFBEAR_ARCH" \
        --repository "$ALPINE_MAIN_REPO" \
        --repository "$ALPINE_COMMUNITY_REPO" \
        --repositories-file /dev/null \
        --allow-untrusted \
        --output "$APK_OUTPUT_SNAPSHOTS" \
        --recursive \
        $WOLFBEAR_PACKAGES

    echo "Generando indices"
    (
        cd "$APK_OUTPUT_SNAPSHOTS"
        rm -f APKINDEX.tar.gz
        apk index -o APKINDEX.tar.gz
        ls -lh APKINDEX.tar.gz
    )

done

cd "$OUTPUT_PATH/"

rm -f apk.zip
zip -r apk.zip apk/