#! /bin/sh
set -euo pipefail

source ./globals

WOLFBEAR_ARCHES="aarch64 x86_64"

WOLFBEAR_PACKAGES="
apk-tools
shadow
util-linux
e2fsprogs
dosfstools
parted
kmod
linux-headers
libc-utils
file
nano
dhcpcd
openresolv
openssh
openssh-server
git
strace
sdl2
sdl2-dev
libdrm
libdrm-dev
mesa-gbm
mesa-dev
mesa-dri-gallium
mesa-egl
libinput
libinput-dev
expat-dev
libffi-dev
libxkbcommon
grub-efi
e2fsprogs-extra
rsync
"

ALPINE_MAIN_REPO="https://dl-cdn.alpinelinux.org/alpine/v3.22/main"
ALPINE_COMMUNITY_REPO="https://dl-cdn.alpinelinux.org/alpine/v3.22/community"

for WOLFBEAR_ARCH in $WOLFBEAR_ARCHES; do
    APK_OUTPUT_SNAPSHOTS="$OUTPUT_PATH/apk/$WOLFBEAR_ARCH"

	echo "Limpiando mirrors anteriores en $APK_OUTPUT_SNAPSHOTS"
	rm -rf "$APK_OUTPUT_SNAPSHOTS"
	mkdir -p "$APK_OUTPUT_SNAPSHOTS"

    echo "Descargando dependencias APK"
	apk fetch \
        --no-cache \
        --cache-dir /dev/null \
        --arch "$WOLFBEAR_ARCH" \
        --repository "$ALPINE_MAIN_REPO" \
        --repository "$ALPINE_COMMUNITY_REPO" \
        --repositories-file /dev/null \
        --allow-untrusted \
        --output "$APK_OUTPUT_SNAPSHOTS" \
        --recursive \
        $WOLFBEAR_PACKAGES

    echo "Generando indices"
    (
        cd "$APK_OUTPUT_SNAPSHOTS"
        rm -f APKINDEX.tar.gz

        echo "Listando .apk en $APK_OUTPUT_SNAPSHOTS..."
        ls -1 *.apk 2>/dev/null | head

        # Evitar que *.apk se quede literal si no hay archivos
        set -- ./*.apk
        if [ "$1" = "./*.apk" ]; then
            echo "ERROR: No se encontraron paquetes .apk en $APK_OUTPUT_SNAPSHOTS, no puedo generar APKINDEX" >&2
            exit 1
        fi

        echo "Total de paquetes a indexar: $#"

        apk index \
            --rewrite-arch "$WOLFBEAR_ARCH" \
            --description "Wolfbear OS Dev APK Index for $WOLFBEAR_ARCH" \
            -o APKINDEX.tar.gz \
            "$@"

        echo "Índice generado:"
        ls -lh APKINDEX.tar.gz

        echo "Contenido del APKINDEX (primeras líneas):"
        tar xzOf APKINDEX.tar.gz APKINDEX | head -20
    )

done

echo "Empaquetando todos los APK en $OUTPUT_PATH/apk.zip"
cd "$OUTPUT_PATH/"

rm -f apk.zip
zip -r apk.zip apk/