#! /bin/sh
set -euo pipefail

source ./globals

if [ "$SYS_ARCH" == "amd64" ]; then
    WOLFBEAR_ARCHES="x86_64"
elif [ "$SYS_ARCH" == "arm64" ]; then
    WOLFBEAR_ARCHES="aarch64"
fi

WOLFBEAR_PACKAGES="
apk-tools
shadow
util-linux
e2fsprogs
dosfstools
parted
kmod
linux-headers
libc-utils
file
nano
dhcpcd
openresolv
openssh
openssh-server
git
strace
sdl2
sdl2-dev
libdrm
libdrm-dev
mesa-gbm
mesa-dev
mesa-dri-gallium
mesa-egl
libinput
libinput-dev
expat-dev
libffi-dev
libxkbcommon
grub-efi
e2fsprogs-extra
rsync
"

ALPINE_MAIN_REPO="https://dl-cdn.alpinelinux.org/alpine/v3.22/main"
ALPINE_COMMUNITY_REPO="https://dl-cdn.alpinelinux.org/alpine/v3.22/community"

for WOLFBEAR_ARCH in $WOLFBEAR_ARCHES; do
    APK_PACKAGES_DOWNLOAD_DIR="$APK_SOURCES_DIR/$WOLFBEAR_ARCH"

    echo "Creating download directory at $APK_PACKAGES_DOWNLOAD_DIR..."
	mkdir -p "$APK_PACKAGES_DOWNLOAD_DIR"

    echo "Downloading APK packages for architecture: $WOLFBEAR_ARCH"
    echo "from repositories: $ALPINE_MAIN_REPO and $ALPINE_COMMUNITY_REPO"
    echo "output path: $APK_PACKAGES_DOWNLOAD_DIR"

	apk fetch \
        --no-cache \
        --cache-dir /dev/null \
        --arch "$WOLFBEAR_ARCH" \
        --repository "$ALPINE_MAIN_REPO" \
        --repository "$ALPINE_COMMUNITY_REPO" \
        --repositories-file /dev/null \
        --allow-untrusted \
        --output "$APK_PACKAGES_DOWNLOAD_DIR" \
        --recursive \
        $WOLFBEAR_PACKAGES

    echo "Generating APKINDEX in path: $APK_PACKAGES_DOWNLOAD_DIR"
    (
        echo "Accessing directory to $APK_PACKAGES_DOWNLOAD_DIR"
        cd "$APK_PACKAGES_DOWNLOAD_DIR"
        rm -f APKINDEX.tar.gz

        echo "Listing contents of download directory: $APK_PACKAGES_DOWNLOAD_DIR"
        ls -1 *.apk 2>/dev/null | head

        # Evitar que *.apk se quede literal si no hay archivos
        set -- ./*.apk
        if [ "$1" = "./*.apk" ]; then
            echo "ERROR: no .apk packages were found in $APK_PACKAGES_DOWNLOAD_DIR. Unable to generate APKINDEX" >&2
            exit 1
        fi

        echo "Total package count to index: $#"

        apk index \
            --rewrite-arch "$WOLFBEAR_ARCH" \
            --description "WolfbearOS APK Index for $WOLFBEAR_ARCH" \
            --allow-untrusted \
            -o APKINDEX.tar.gz \
            "$@"

        echo "Generated index:"
        ls -lh APKINDEX.tar.gz
    )

done

echo "All APK packages have been downloaded and indexed successfully."