#! /bin/sh
set -euo pipefail

source ./globals

echo "Copying packaged apk files to compiled directory at $APK_COMPILED_DIR"

rsync -a --delete "$APK_SOURCES_DIR/" "$APK_COMPILED_DIR/"

echo "APK packages copied successfully to $APK_COMPILED_DIR"