#!/bin/sh
set -e

source ./globals

cd "$BUSYBOX_SOURCE_CODE_DIR"

PATCH="$BUSYBOX_PATCHES_DIR/wolfbear-dialog_busybox_1.37.0.patch"

echo "Probando parche: $PATCH"

if patch --dry-run --forward -p0 < "$PATCH"; then
    echo "Aplicando parches para ncurses fix en Alpine"
    patch -p0 < "$PATCH"
    echo "El parche fue aplicado exitosamente"
else
    echo "El parche de ncurses fue aplicado exitosamente"
fi

if [ "$SYS_ARCH" = "arm64 "]; then
    PATCH="$BUSYBOX_PATCHES_DIR/busybox-arm64-shaNI.patch"
    if patch --dry-run --forward -p0 < "$PATCH"; then
        echo "Aplicando parches para shaNi fix en Alpine"
        patch -p0 < "$PATCH"
        echo "El parche fue aplicado exitosamente"
    else
        echo "El parche de ncurses fue aplicado exitosamente"
    fi
fi