#!/bin/sh
set -euo pipefail

source ./globals

cd $ROOT_PATH

echo "Sincronizando archivo de configuración busybox '$BUSYBOX_SOURCE_CODE_DIR'"

echo "Eliminando archivo de configuración si existe en '$BUSYBOX_SOURCE_CODE_DIR/.config'"
rm -f "$BUSYBOX_SOURCE_CODE_DIR"/.config

CONFIG_IN_PROJECT="$BUSYBOX_CONFIGS_PATH/busybox-config-$SYS_ARCH"

CONFIG_IN_BUSYBOX_DIR="$BUSYBOX_SOURCE_CODE_DIR/.config"

echo "Copiando archivo de configuración desde '$CONFIG_IN_PROJECT' hasta '$CONFIG_IN_BUSYBOX_DIR'" 1
cp $CONFIG_IN_PROJECT $CONFIG_IN_BUSYBOX_DIR

echo "Archivo de configuración sincronizado exitosamente en '$CONFIG_IN_BUSYBOX_DIR'"