#!/bin/sh
set -e

source ./globals

rm -rf "$BUSYBOX_SOURCE_CODE_DIR/.config"
cp "$BUSYBOX_CONFIGS_PATH/busybox-$SYS_ARCH" "$BUSYBOX_SOURCE_CODE_DIR/.config"

cd "$BUSYBOX_SOURCE_CODE_DIR"
make -j"$(nproc)"

rm -f busybox.zip
zip -r busybox.zip .

mv busybox.zip "$BUSYBOX_COMPILED_DIR"