#!/bin/sh
set -euo pipefail

source ./globals

cd $ROOT_PATH

echo "Revisando que parches son necesarios según la arquitectura"
cd $BUSYBOX_SOURCE_CODE_DIR

if [ "$SYS_ARCH" = 'arm64' ]; then
	echo "Verificando parches para la arquitectura ARM64"

	if patch --dry-run --forward -p0 < $BUSYBOX_PATCHES_DIR/busybox-arm64-shaNI.patch > /dev/null; then
		echo "Aplicando parches para la arquitectura ARM64"
		patch -p0 < $BUSYBOX_PATCHES_DIR/busybox-arm64-shaNI.patch
	else
		echo "Busybox ya tiene el parche para ARM64" 0.5
	fi
fi

echo "Verificando parches para las arquitecturas ARM64/AMD64"

if patch --dry-run --forward -p0 < $BUSYBOX_PATCHES_DIR/001-busybox-disable-dochecklxdialog.patch > /dev/null; then
	echo "Aplicando parches para la ambas arquitecturas"
	patch -p0 < $BUSYBOX_PATCHES_DIR/001-busybox-disable-dochecklxdialog.patch
else
	echo "Busybox ya tiene el parche instalado para ambas arquitecturas" 0.5
fi

echo "Proceso de parcheo terminado exitosamente"

cd $ROOT_PATH
