#!/bin/sh
set -e

source ./globals

echo "Compiling Busybox source code in '$BUSYBOX_SOURCES_DIR' for arch '$SYS_ARCH'"

cd "$BUSYBOX_SOURCES_DIR"
make -j"$(nproc)"

echo "Compilation of Busybox completed successfully"