#!/bin/sh
set -e

source ./globals

echo "Compiling Busybox source code in '$BUSYBOX_SOURCES_DIR' for arch '$SYS_ARCH'"

cd "$BUSYBOX_SOURCES_DIR"
make -j"$(nproc)"

rm -rf "$BUSYBOX_SOURCES_DIR/wolfbear-compilation"
mkdir -p "$BUSYBOX_SOURCES_DIR/wolfbear-compilation"

make CONFIG_PREFIX="$BUSYBOX_SOURCES_DIR/wolfbear-compilation" install

echo "Compilation and installation of Busybox completed successfully"