#!/bin/sh
set -e

#!/bin/sh
set -e

source ./globals

echo "Compressing Busybox source code in '$BUSYBOX_SOURCES_DIR' into zip file"

cd "$BUSYBOX_SOURCES_DIR/wolfbear-compilation"
rm -rf busybox.zip

zip -r busybox.zip .

mv "busybox.zip" "$BUSYBOX_COMPILED_DIR/"

cd "$BUSYBOX_COMPILED_DIR/.."

rm -rf "$BUSYBOX_SOURCES_DIR/wolfbear-compilation"