#!/bin/sh
set -euo pipefail
source $SCRIPTS_DIR/util-log

SCRIPT_NAME=$0

log_message $SCRIPT_NAME "Sincronizando archivo de configuración busybox '$DEPENDENCY_BUSYBOX_DIR'"

debug_message $SCRIPT_NAME "Eliminando archivo de configuración si existe en '$DEPENDENCY_BUSYBOX_DIR/.config'"
rm -f "$DEPENDENCY_BUSYBOX_DIR"/.config

CONFIG_IN_PROJECT="$CONFIG_FILES_DIR/busybox-config-$SYS_ARCH"
CONFIG_IN_BUSYBOX_DIR="$DEPENDENCY_BUSYBOX_DIR/.config"

debug_message $SCRIPT_NAME "Copiando archivo de configuración desde '$CONFIG_IN_PROJECT' hasta '$CONFIG_IN_BUSYBOX_DIR'" 1
cp $CONFIG_IN_PROJECT $CONFIG_IN_BUSYBOX_DIR

log_message $SCRIPT_NAME "Archivo de configuración sincronizado exitosamente en '$CONFIG_IN_BUSYBOX_DIR'"