#!/bin/sh
set -euo pipefail
source $SCRIPTS_DIR/util-log

SCRIPT_NAME=$0

log_message $SCRIPT_NAME "El usuario solicitó abrir el menú de configuración de Busybox para cambiar la configuración"
debug_message $SCRIPT_NAME "Abriendo directorio '$DEPENDENCY_BUSYBOX_DIR'"

cd $DEPENDENCY_BUSYBOX_DIR
pwd

debug_message $SCRIPT_NAME "Solicitando 'make menuconfig'"
make menuconfig

PROJECT_CONFIG="$WOLFBEAR_OS_DIR/config/busybox-config-$SYS_ARCH"
DEPENDENCY_CONFIG="$DEPENDENCY_BUSYBOX_DIR/.config"

debug_message $SCRIPT_NAME "Sincronizando cambios hechos desde '$DEPENDENCY_CONFIG' hasta '$PROJECT_CONFIG'"

rm -f $PROJECT_CONFIG
cp $DEPENDENCY_CONFIG $PROJECT_CONFIG

log_message $SCRIPT_NAME "Archivo de configuración sincronizado exitosamente en '$PROJECT_CONFIG'"