#!/bin/sh
set -euo pipefail
source $SCRIPTS_DIR/util-log

SCRIPT_NAME=$0

log_message $SCRIPT_NAME "Compilación de Busybox"

debug_message $SCRIPT_NAME "Abriendo directorio '$DEPENDENCY_BUSYBOX_DIR'"
cd $DEPENDENCY_BUSYBOX_DIR

debug_message $SCRIPT_NAME "Solicitando compilación de Busybox make"
make -j$(nproc)

debug_message $SCRIPT_NAME "Instalando Busybox en directorio '$DEPENDENCY_BUSYBOX_COMPILED_DIR'"
mkdir -p $DEPENDENCY_BUSYBOX_COMPILED_DIR
make CONFIG_PREFIX=$DEPENDENCY_BUSYBOX_COMPILED_DIR install

log_message $SCRIPT_NAME "Busybox ha sido compilado exitosamente en '$DEPENDENCY_BUSYBOX_COMPILED_DIR'"

