#!/bin/sh
set -euo pipefail

source ./globals

echo "Downloading Linux '$LINUX_KERNEL_SOURCES_DIR'"

if [ ! -d "$LINUX_KERNEL_SOURCES_DIR" ] || [ -z "$(ls -A "$LINUX_KERNEL_SOURCES_DIR")" ]; then
	echo "Linux kernel sera descargado desde su repositorio oficial"
	git clone -b v$LINUX_KERNEL_VERSION --single-branch https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git $LINUX_KERNEL_SOURCES_DIR

	echo "Linux kernel se ha descargado exitosamente"
else 
	echo "No es necesario descargar Linux Kernel ya que fue encontrado en la carpeta de dependencias"
fi
