#!/bin/sh
set -euo pipefail

source ./globals

echo "Setting up config file in '$LINUX_KERNEL_SOURCES_DIR' for arch '$SYS_ARCH'"

echo "Removing prefious configuration"
rm -f "$LINUX_KERNEL_SOURCES_DIR"/.config

echo "Copyng config file"
cp "$LINUX_KERNEL_CONFIG_DIR/$SYS_ARCH".config "$LINUX_KERNEL_SOURCES_DIR"/.config

echo "Successfully copied config file into Linux source directory"