#!/bin/sh
set -euo pipefail

source ./globals

echo "Starting make clean for Linux kernel sources at: $LINUX_KERNEL_SOURCES_DIR"

cd $LINUX_KERNEL_SOURCES_DIR
make clean

echo "Clean finished successfully."