#!/bin/sh
set -euo pipefail

source ./globals

echo "Starting Linux compilation in directory: $LINUX_KERNEL_SOURCES_DIR"
cd $LINUX_KERNEL_SOURCES_DIR

echo "Requesting kernel compilation with multiple cores"
make -j$(nproc)

echo "Linux kernel compilation completed successfully."