#!/bin/sh
set -euo pipefail

source ./globals

echo "Moving compiled sources into '$LINUX_KERNEL_COMPILED_DIR'"

if [ "$SYS_ARCH" = "arm64" ]; then
  SRC_ARCH=arm64
  IMG=Image
elif [ "$SYS_ARCH" = "amd64" ] || [ "$SYS_ARCH" = "x86_64" ]; then
  SRC_ARCH=x86
  IMG=bzImage
else
  echo "Unknown architecture '$SYS_ARCH'"
  exit 1
fi

IMAGE_DIR="$LINUX_KERNEL_SOURCES_DIR/arch/$SRC_ARCH/boot/$IMG"

echo "Moving kernel image to compiled directory"
mv $IMAGE_DIR "$LINUX_KERNEL_COMPILED_DIR/"

echo "Linux kernel image moved successfully into $LINUX_KERNEL_COMPILED_DIR"